version: '3.7'
services:
  server:
    build:
      context: agg-client-demo
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: "8080"
    networks:
      - agg-network

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - agg-network


networks:
  agg-network:
    driver: bridge